### PR TITLE
Increase readability

### LINKED ISSUE #55: coalahtml/tree.py: Increase readability
In https://github.com/coala-analyzer/coala-html/blob/master/coalahtml/tree.py#L40 
`if not prev_node.child.get(new_node.name, None):` is better to change to 
`if new_node.name not in prev_node.child:`. It'll be easier to read and it's more correct, as `None` or `False` can be key in general.

### PR DESCRIPTION
**Pull request by sotanishy**
In coalahtml/tree.py#L40
if not prev_node.child.get(new_node.name, None): is changed to
if new_node.name not in prev_node.child:. It's easier to read and it's more correct, as None or False can be key in general.

close #55

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by prnvdixit** [comment]
Also, please squash your commits into one commit only - A single change should be reflected in single commit only 😃

**Comment by prnvdixit** [comment]
@sotanishy Also, next time you can omit the directory_name from the Shortlog as that may overshoot the 50 chars limit in some cases 😉... Specifying file name is enough usually 👍

**Comment by prnvdixit** [comment]
ack 680bde29bd2677615c74e7262a276d0d0fc51912

**Comment by sotanishy** [comment]
How do I remove the process/wip label?

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
