### PR TITLE
views/main.html: Fix closing tag for h3

### PR DESCRIPTION
**Pull request by sahilarora535**
Fixes https://github.com/coala/coala-html/issues/107

### CODE REVIEW

**Comment by dracarys09** [comment]
ack 6cf4e2b07f9033d1062c1e68bca83e53d8b223f2

**Comment by sims1253** [comment]
ack 6d6900d5a33fde2811a0beb10e1e25d58f629768

**Comment by sims1253** [comment]
you have to rebase this so we can merge it. Take a look at coala.io/rebase

**Comment by sahilarora535** [comment]
@sims1253 Done.

**Comment by Mariatta** [comment]
Seems like rebase is still needed. Can you please try again?

**Comment by sils** [comment]
2448ea1 is ready

**Comment by sils** [comment]
rebase (or cherry pick from maintainer alternatively) needed

**Comment by sahilarora535** [comment]
@Mariatta @sils Rebased again.

**Comment by sils** [comment]
ACK 38105ae79ac8f80ba714f864a75791a7f62710dc

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
