### PR TITLE
files.css: Add coala ignore around long lines

### PR DESCRIPTION
**Pull request by Mixih**
Added the ignore to squash the unnessesary error
about the lines that are 1 char over limit.

Fixes https://github.com/coala/coala-html/issues/91

- [x] I have rebased properly. Please see this for a tutorial.
- [x] I have gone through the commit guidelines and I've followed them:
- [x] I have followed the guidelines for the commit shortlog.
- [x] I have followed the guidelines for the commit body.
- [x] I have included the issue URL.
- [x] I have used the Fixes keyword if the commit fixes a real bug and the Closes keyword if it adds a feature/enhancement. See more here.
- [x] I have run all the tests and they all pass. That includes that all CI (below) is green - if GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### CODE REVIEW

**Comment by jayvdb** [comment]
ack 4490cf0

**Comment by jayvdb** [comment]
@rultor merge

**Comment by tushar-rishav** [comment]
@rultor merge

**Comment by tushar-rishav** [comment]
@rultor merge

**Pull request merged**
