### PR TITLE
coala-html: Update to coala 0.9

### PR DESCRIPTION
**Pull request by Mixih**
Change the coala_decorator import to coala_util
Remove depreciated parameter auto_apply from
run_coala

Closes https://github.com/coala/coala-html/issues/87

### CODE REVIEW

**Comment by Mixih** [comment]
Not all files that should be listed are getting listed in my local system. Still testing to see whether this is a consistent problem, or a fluke with my environment.

**Comment by Mixih** [comment]
I was a idiot and failed to clean up my python environment before testing my changes. It works just fine. However, just to be safe, the reviewer should install this branch with coala-bears==0.9 (NOT PRE) in a clean virtual env to confirm all works.

**Comment by sils** [comment]
Coala -> coala

**Comment by sils** [comment]
otherwise good :)

**Comment by aptrishu** [comment]
ack a7b74f2

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
