### PR TITLE
Readme.rst: Fix GETTING INVOLVED link

### LINKED ISSUE #128: Fix GETTING INVOLVED link in README.rst
The current link is pointing to old docs i.e. `http://coala.readthedocs.org/en/latest/Getting_Involved/README.html` change it to `https://coala.io/#/getinvolved`
label: difficulty/newcomer
Opened by @aashutoshrathi at [Gitter](https://gitter.im/coala/coala?at=59f84149b20c6424296c2453)

### PR DESCRIPTION
**Pull request by prashant0598**
Readme.rst: Fix GETTING INVOLVED link

This entrypoint ensures that link is not pointing to old docs i.e. http://coala.readthedocs.org/en/latest/Getting_Involved/README.html but to https://coala.io/#/getinvolved

Closes #128 

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by prashant0598** [comment]
@prnvdixit commit amended accordingly 😃

**Comment by prnvdixit** [comment]
@prashant0598 Wanna finish this off? 😉
Just amend the commit to
```
README.rst: Fix getting involved link

This ensures that link pointing to "Getting involved information" page is correct.

Closes #128
```
using ```git commit -a --amend```. 👍

**Comment by anshumanv** [comment]
Am i assigned to this for reviewing?

**Comment by prashant0598** [comment]
@anshumanv by mistake I merged ur previous merged commit with my branch so u got assigned :smile:

**Comment by anshumanv** [comment]
Ah I see, no issues then. :+1:

**Comment by jayvdb** [comment]
@prashant0598 , your commit message is still wrong.  Please fix it.

**Comment by jayvdb** [comment]
Closing due to inactivity

**Pull request closed without merging**
